spotify-web-api-java/spotify-web-api-java

src/main/java/com/wrapper/spotify/SpotifyHttpManager.java
This is currently supported in the latest version, but as the "commons-httpclient" lib was updated, the existing code was removed due to compatibility issues. It's is a crucial fix, since without it, you're not able to make requests with URL parameters.
=> Add support for building a query string from a list of parameters

src/main/java/com/wrapper/spotify/Api.java, src/main/java/com/wrapper/spotify/model_objects/Track.java
~ Javadoc added for Api & Api.Builder
~ Javadoc added for Track
More are to come. 
See #95 
But should we add Javadoc to the setter methods in builder classes of model objects too? I think in many classes (like Track.Builder) these methods are only called by it's corresponding JsonUtil, so there would be no need for documentation. But there are quite a few exceptions though, like Api.Builder (which isn't a model object), where you have to call them yourself often. (set auth token, set refresh token...) In such cases it would be useful.
=> Javadoc documentation

.gitignore, src/main/java/com/wrapper/spotify/Api.java, src/test/java/com/wrapper/spotify/ApiTest.java
Updated the api call to support passing in true/false for show_dialog parameter. This can be used to force a user to sign in and ignore cookies from browser. Very useful.
I also updated the gitignore to ignore eclipse files (yeah i have not converted to intellij lol)
=> API Authorize URL | Show Dialog Support

src/main/java/com/wrapper/spotify/Api.java, src/main/java/com/wrapper/spotify/JsonUtil.java, src/main/java/com/wrapper/spotify/methods/TracksForAlbumRequest.java
Small change to have an option to find tracks given an album, something like:
https://api.spotify.com:443/v1/search?q=album:Sonic%20Highways&type=track
=> Adding a method to get all tracks given an album

src/main/java/com/wrapper/spotify/requests/data/browse/GetRecommendationsRequest.java, src/main/java/com/wrapper/spotify/requests/data/follow/FollowArtistsOrUsersRequest.java, src/main/java/com/wrapper/spotify/requests/data/follow/UnfollowArtistsOrUsersRequest.java, src/main/java/com/wrapper/spotify/requests/data/library/RemoveAlbumsForCurrentUserRequest.java, src/main/java/com/wrapper/spotify/requests/data/library/RemoveUsersSavedTracksRequest.java, src/main/java/com/wrapper/spotify/requests/data/library/SaveAlbumsForCurrentUserRequest.java, src/main/java/com/wrapper/spotify/requests/data/library/SaveTracksForUserRequest.java, src/main/java/com/wrapper/spotify/requests/data/playlists/AddTracksToPlaylistRequest.java, src/main/java/com/wrapper/spotify/requests/data/playlists/ReplacePlaylistsTracksRequest.java, src/main/java/com/wrapper/spotify/requests/data/tracks/GetSeveralTracksRequest.java
While looking over the new implementation, I happened to see some minor inconsistencies:
- In one instance, the ordering was flipped for x <= limit && limit <= y, it's also inconsistent with the fact that in all other cases >=  and <= is preferred over > and < (not particularly important)
- In a few instances, there was a limit for the number of ids, tracks, etc but there wasn't an assert in the function checking that that limit was respected
- In one instance the limit described in the Javadoc/Web API reference doesn't match the assert limit in the code
=> Fix minor style/reference inconsistencies

src/main/java/com/wrapper/spotify/SpotifyHttpManager.java, src/main/java/com/wrapper/spotify/exceptions/detailed/BadRequestException.java, src/main/java/com/wrapper/spotify/exceptions/detailed/TooManyRequestsException.java
Spotify gives you a Retry-After header when API-Request limit is exceeded.
This header is extracted and set to variable inside TooManyRequestsException.
Documentation: https://beta.developer.spotify.com/documentation/web-api/#rate-limiting
=> Adds Retry-After Variable to TooManyRequestsException

examples/data/playlists/RemoveTracksFromPlaylistExample.java, src/main/java/com/wrapper/spotify/HttpDeleteBody.java, src/main/java/com/wrapper/spotify/IHttpManager.java, src/main/java/com/wrapper/spotify/SpotifyHttpManager.java, src/main/java/com/wrapper/spotify/requests/AbstractRequest.java, src/main/java/com/wrapper/spotify/requests/data/playlists/RemoveTracksFromPlaylistRequest.java, src/test/java/com/wrapper/spotify/TestUtil.java, src/test/java/com/wrapper/spotify/requests/data/playlists/RemoveTracksFromPlaylistRequestTest.java
Remove tracks on playlist request (https://developer.spotify.com/web-api/remove-tracks-playlist/) requires that the http delete body contains formatting like
`{ "tracks": [{ "uri": "spotify:track:4iV5W9uYEdYUVa79Axb7Rh" },{"uri": "spotify:track:1301WleyT98MSxVHPZCA6M" }] }`
This PR adds a method that allows a body in the http delete method as well as updates the formatting of the tracks array so that it matches what spotify expects.
=> fix remove tracks from playlist request 

src/main/java/com/wrapper/spotify/SpotifyApi.java, src/main/java/com/wrapper/spotify/model_objects/specification/PlayHistory.java, src/main/java/com/wrapper/spotify/model_objects/specification/PlaylistTrack.java, src/main/java/com/wrapper/spotify/model_objects/specification/SavedAlbum.java, src/main/java/com/wrapper/spotify/model_objects/specification/SavedTrack.java, src/main/java/com/wrapper/spotify/requests/data/browse/GetListOfFeaturedPlaylistsRequest.java, src/main/java/com/wrapper/spotify/requests/data/player/GetCurrentUsersRecentlyPlayedTracksRequest.java
This commit introduces a ThreadLocal cache for the SimpleDateFormat in question (`SpotifyApi.SIMPLE_DATE_FORMAT`). This ensures that the format is never shared between threads, which could otherwise lead to problems as it is not thread safe by itself.
The public field was replaced with a private one and two methods, for parsing and formatting.
All changes to classes unrelated to `SpotifyApi` are just minor adjustments to make them use the new methods instead.
All existing tests passed and this is not really a major change, but some more testing is probably still a good idea.
* No unit test(s). Suggestions on how to test that behaviour are welcome
* I am not quite sure where the comment describing the format belongs now
* Not quite sure whether it matches the styleguide, but I did also not …
=> Possible fix for #140

src/main/java/com/wrapper/spotify/model_objects/miscellaneous/AudioAnalysisSection.java, src/main/java/com/wrapper/spotify/model_objects/miscellaneous/AudioAnalysisSegment.java
sections and segments do not contain a "measure" object in json, they contain the 3 elements (start, duration, confidence) as top-level objects. This means that the code does not return a measure object because it cannot find a measure object in the json, so it skips parsing that section.
Implemented change means that the code no longer attempts to pull a measure object out of the segment/section json, and instead passes the entire segment/section json object to the AudioAnalysisMeasure parser.
=> Fix issue where measure was not being parsed correctly in segment and section

src/main/java/com/wrapper/spotify/SpotifyHttpManager.java
I created PR in case anyone needs to set custom timeout for http client that can prevent potential issues with 'infinite http requests' (that I have observed).
Also I noticed one potential problem with SpotifyHttpManager but decided not to change code because I am not aware of intentions why 'CloseableHttpClient httpClient' is a static field. At least for me it caused troubles when order of initialization was different for 'custom http client' and 'default http client'.
In other words this looks like a side side effect that can take place when 'custom httpClient' is initialized first, then it can be overridden by other instances of SpotifyHttpManager class e.g. created by 'new SpotifyApi.Builder()'.
=> Add ability to set http request timeouts in HttpManager

src/main/java/com/wrapper/spotify/model_objects/special/SearchResult.java
I forgot to fix the Javadoc SearchResults.class typos in the source files. The Javadoc typos will appear again once it is generated the next time.
=> Fixing the same typos in the source files.

README.md
This change adds the code coverage results of develop branch to **README.md**, which will let the visitors and the current developers see the results directly at the repo's homepage!
Thanks!
=> Adding the CodeCov results to README.md

.travis.yml, pom.xml, travis/code_cov.sh
Earlier, I added CodeCov code coverage using the Cobertura plugin which does not support the latest versions of Java.
Finally, I set up code coverage using JaCoCo plugin and it supports code coverage for all the versions of Java.
=> CodeCov for all the builds

README.md, examples/data/player/AddItemToUsersPlaybackQueueExample.java, src/main/java/com/wrapper/spotify/SpotifyApi.java, src/main/java/com/wrapper/spotify/requests/data/player/AddItemToUsersPlaybackQueueRequest.java, src/test/java/com/wrapper/spotify/requests/data/player/AddItemToUsersPlaybackQueueRequestTest.java
adds support for new API-endpoint https://developer.spotify.com/documentation/web-api/reference/player/add-to-queue/
implements #194
=> Add Support for Adding Items to User's Playback Queue 

pom.xml
The slf4j-simple dependency conflicts with logback-classic.
As they both are implementations for the slf4j API the following will occur
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/duncte123/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/duncte123/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.30/e606eac955f55ecf1d8edcccba04eb8ac98088dd/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type …
```
=> Change slf4j to api dependency

README.md
kaaes's lib is great, but hasn't been updated since 2016. spotify-web-api-kotlin includes wrappers for spotify-auth and is consistently updated.
=> Add adamint/spotify-web-api-kotlin as a valid option for Spotify Android degvelopment

src/main/java/se/michaelthelin/spotify/model_objects/miscellaneous/Device.java, src/test/fixtures/requests/data/player/GetInformationAboutUsersCurrentPlaybackRequest.json, src/test/fixtures/requests/data/player/GetUsersAvailableDevices.json
fixes #300 
- Device includes flag, it's getter, setter, and factory.
- Test data modified to include the flag.
- All existing tests pass.
Functionality tested live :
https://user-images.githubusercontent.com/50697488/184509305-2b3ec99a-6685-4269-94a3-9e04aa375425.mov
=> (#300) Wrap `is_private_session` flag 

src/main/java/se/michaelthelin/spotify/model_objects/miscellaneous/Device.java, src/test/fixtures/requests/data/player/GetUsersAvailableDevices.json, src/test/java/se/michaelthelin/spotify/requests/data/player/GetUsersAvailableDevicesTest.java
Adding the "supports_volume" field in Device.java
https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices
=> feat(device): add `supports_volume` field

README.md, examples/data/library/CheckUsersSavedEpisodesExample.java, examples/data/library/GetUsersSavedEpisodesExample.java, examples/data/library/RemoveUsersSavedEpisodesExample.java, examples/data/library/SaveEpisodesForCurrentUserExample.java, src/main/java/se/michaelthelin/spotify/SpotifyApi.java, src/main/java/se/michaelthelin/spotify/model_objects/miscellaneous/SavedEpisode.java, src/main/java/se/michaelthelin/spotify/model_objects/specification/SavedEpisode.java, src/main/java/se/michaelthelin/spotify/requests/data/library/CheckUsersSavedEpisodesRequest.java, src/main/java/se/michaelthelin/spotify/requests/data/library/GetUsersSavedEpisodesRequest.java, src/main/java/se/michaelthelin/spotify/requests/data/library/RemoveUsersSavedEpisodesRequest.java, src/main/java/se/michaelthelin/spotify/requests/data/library/SaveEpisodesForCurrentUserRequest.java, src/test/fixtures/requests/data/library/CheckUsersSavedEpisodesRequest.json, src/test/fixtures/requests/data/library/GetUsersSavedEpisodesRequest.json, src/test/java/se/michaelthelin/spotify/ITest.java, src/test/java/se/michaelthelin/spotify/requests/data/library/CheckUsersSavedEpisodesRequestTest.java, src/test/java/se/michaelthelin/spotify/requests/data/library/GetUsersSavedEpisodesRequestTest.java, src/test/java/se/michaelthelin/spotify/requests/data/library/RemoveUsersSavedEpisodesRequestTest.java, src/test/java/se/michaelthelin/spotify/requests/data/library/SaveEpisodesForCurrentUserRequestTest.java
Added 4 episode endpoints which were added to Spotify API a couple years ago.
- [Get User's Saved Episodes](https://developer.spotify.com/documentation/web-api/reference/get-users-saved-episodes)
- [Save Episodes for Current User](https://developer.spotify.com/documentation/web-api/reference/save-episodes-user)
- [Remove User's Saved Episodes](https://developer.spotify.com/documentation/web-api/reference/remove-episodes-user)
- [Check User's Saved Episodes](https://developer.spotify.com/documentation/web-api/reference/check-users-saved-episodes)
Note, these endpoints are actually still in beta, from documentation: `This API endpoint is in beta and could change without warning.`.
=> feat: add 4 episode endpoints

.github/workflows/ci.yml, lgtm.yml
Waiting for:
- ~~https://github.com/actions/setup-java/pull/538~~
=> ci: use java 21

src/main/java/se/michaelthelin/spotify/model_objects/special/PlaybackQueue.java, src/main/java/se/michaelthelin/spotify/model_objects/specification/PlaylistTrack.java, src/main/java/se/michaelthelin/spotify/model_objects/utils/PlaylistItemFactory.java
Hello everyone, I'm submitting this refactor to learn how to contribute to open source projects at the same time as I study "code smells" and I analyzed this at first and found this improvement
- Refactoring Guru- [Duplicate Code](https://refactoring.guru/pt-br/smells/duplicate-code)
- Java Rule PMD - [AvoidDeeplyNestedIfStmts](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_design.html#avoiddeeplynestedifstmts)
This rule recommends avoiding code that contains deeply nested if-then statements to improve code readability.
=> Added util factory class to remove duplicated code

src/main/java/se/michaelthelin/spotify/model_objects/specification/Track.java, src/test/fixtures/requests/data/tracks/GetTrackRequestLocal.json, src/test/java/se/michaelthelin/spotify/requests/data/tracks/GetTrackRequestLocalTest.java
As discussed in https://github.com/spotify-web-api-java/spotify-web-api-java/issues/381
=> fix: add temporary workaround for local files' `duration_ms` anomaly

examples/data/follow/CheckUsersFollowPlaylistExample.java, src/main/java/se/michaelthelin/spotify/SpotifyApi.java, src/main/java/se/michaelthelin/spotify/requests/data/follow/CheckUsersFollowPlaylistRequest.java, src/test/java/se/michaelthelin/spotify/requests/data/follow/CheckUsersFollowPlaylistRequestTest.java
As discussed in #395 , this is a pull request linked to #396 that removes the usage of the `owner_id` param in CheckUsersFollowPlaylist requests since it is no longer in documentation and might break in the futur. The methods using `owner_id` param are now deprecated, allowing users to update their codes before removal.
=> Deprecate usage of owner_id param in CheckUsersFollowPlaylist requests to match the updated endpoint

src/main/java/se/michaelthelin/spotify/SpotifyHttpManager.java
Builds upon https://github.com/spotify-web-api-java/spotify-web-api-java/pull/407, keeping the setter-only builder architecture.
=> feat(http): expose connection manager

src/main/java/se/michaelthelin/spotify/SpotifyHttpManager.java
* expose http connection mgr with backwards compatibility
* add HttpClientConnectionManager to SpotifyHttpManager.builder
* add SpotifyHttpManager.Builder.getConnectionManager to handle default
Similar to #375, but providing backwards compatibility to be included in a 8.4.2.
The default usage does not change, however adding support for PoolingHttpClientConnectionManager would look like this:
```java
var spotifyApi = SpotifyApi.builder()
.setHttpManager(new SpotifyHttpManager.Builder()
.setConnectionManager(new PoolingHttpClientConnectionManager())
.build())
.setClientId("foo")
.setClientSecret("bar")
.build();
```
=> expose backward compatible connection mgr

src/main/java/se/michaelthelin/spotify/model_objects/specification/Track.java, src/test/fixtures/requests/data/tracks/GetTrackRequestLocal.json
* https://community.spotify.com/t5/Spotify-for-Developers/duration-ms-includes-nonsense-JSON/m-p/5753768
=> fix(track): remove special-case handling of local `duration_ms`

src/main/java/se/michaelthelin/spotify/model_objects/specification/PlaylistSimplified.java
This PR adds the description field to PlaylistSimplified model. For reference, see
- https://developer.spotify.com/documentation/web-api/reference/get-featured-playlists
- https://developer.spotify.com/documentation/web-api/reference/get-a-list-of-current-users-playlists
=> add description field to PlaylistSimplified model
